- name: install apache2 and libapache2-mod-php packages for Ubuntu
  tags: apache,apache2,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: "{{ apache_package_name }}" 
    state: started
    enabled: yes

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

